services:
  - type: web
    name: sih-asdp
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_FOLDER
        value: /data/uploads
      - key: SQLALCHEMY_DATABASE_URI
        value: sqlite:////data/app.db
    healthCheckPath: /
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

