services:
  - type: web
    name: sih-asdp
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_FOLDER
        value: uploads
      - key: SQLALCHEMY_DATABASE_URI
        value: sqlite:///app.db
      - key: MAX_CONTENT_LENGTH
        value: "16777216"
    healthCheckPath: /

